import "../styles/globals.css";
import { AppProps } from "next/app";
import Header from "../components/Header";
import Head from "next/head";
import { Provider } from "react-redux";
import { store } from "../store/store";
function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Games for all</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <Header />
      <Provider store={store}>
        <Component {...pageProps} />
      </Provider>
    </>
  );
}

export default MyApp;
