import '../styles/globals.css'
import { AppProps } from 'next/app'
import Header from '../components/Header'
import Head from 'next/head'
function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Games for all</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <Header />
      <Component {...pageProps} />
    </>
  )
}

export default MyApp
